title: SKryptz | qb-burglary documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs

url: https://skryptz5m.github.io/burglary-docs/

search_enabled: false

logo: "/assets/images/sklogo.png"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  required:
    title: Requirements
    color: green

aux_links:
  Tebex: https://skryptz.tebex.io/package/5026669
  Discord: https://discord.gg/FnbGUkWxHY
