title: SKryptz | qb-burglary documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://skryptz5m.github.io/burglary-docs/

color_scheme: dark

search_enabled: false

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
